Ensure correct permissions for salt-cloud generated files
saltstack-formulas/salt-formula pull request #501
Opened 2021-03-19 11:23 UTC by pprkut

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

### Describe the changes you're proposing

salt-cloud creates the initial minion config and certificates with the permissions of the user it's connected as.
These checks make sure the permissions are the same as in a non salt-cloud setup.

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2021-03-19 13:03 UTC, pprkut commented
Not sure about the failing tests :-/

It looks like on those systems the pki-dir is different from /etc/salt/pki, but no config (that I can find) that would define it.
Am I missing something?

2021-08-09 22:59 UTC, noelmcloughlin commented
@pprkut sorry for delay getting feedback.  Could you add `makedirs: true` to your file.directory states?

The CI error is : _No directory to create /etc/salt/pki/minion in_

2021-08-24 21:07 UTC, noelmcloughlin commented
ping @pprkut ;-)

2021-11-06 09:25 UTC, vutny requested changes
Hi @pprkut 
I think, those added file states should to be done with cross-platform support, now they have parameters supported on GNU/Linux only. Please find examples how to render states for different operating systems in the modified file.

2021-11-06 09:25 UTC, vutny commented on salt/minion.sls
> +    - group: root
On *BSD systems including MacOS, IIRC group `root` does not exist.

2021-11-06 09:25 UTC, vutny commented on salt/minion.sls
> +    - mode: 640
Also file mode is not supported on Windows.

2021-12-26 13:13 UTC, pprkut commented
@vutny I think I have that covered now

2021-12-26 15:49 UTC, pprkut commented
Hmm, the windows tests seem to stumble over the group now. I thought that was ignored on windows?

2021-12-26 23:31 UTC, noelmcloughlin commented
Hello @pprkut 
Windows should be easy fix hopefully, see https://github.com/saltstack-formulas/docker-formula/pull/299/files

2021-12-27 13:23 UTC, noelmcloughlin commented
I think Windows group needs  `{% if grains['kernel'] != 'Windows' %}` wrapped

2021-12-27 13:36 UTC, pprkut commented
I see the windows states failing on this though:
```
The following packages failed to install/update: salt-minion-py3
```

2021-12-27 14:11 UTC, pprkut commented
I'm afraid I'm a bit lost now on the windows failures :(
Since one of them succeeded, I'm assuming it *should* work fine generally. The remaining failures *look* unrelated to my changes, but I can't be sure. Can someone with more knowledge about windows have a look?

2021-12-27 14:43 UTC, myii commented
> I'm afraid I'm a bit lost now on the windows failures :( Since one of them succeeded, I'm assuming it _should_ work fine generally. The remaining failures _look_ unrelated to my changes, but I can't be sure. Can someone with more knowledge about windows have a look?

@pprkut Yes, the failures are unrelated to your changes.  Our Windows Vagrant boxes were updated to `3004` recently, which have led to these failures.

@noelmcloughlin @vutny Once you're happy with the proposed changes, please feel free to merge.

2021-12-27 17:53 UTC, noelmcloughlin commented
Thanks @vutny for review. Thanks @pprkut  for rescuing the PR.

2021-12-27 17:53 UTC, merged