docs(readme): add documentation regarding salt.formula and salt.master, addressing #326
saltstack-formulas/salt-formula pull request #507
Opened 2021-05-26 21:33 UTC by droope

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

This addresses #326, small doc change.

### Describe the changes you're proposing

Some small documentation to make it easier for new users.

### Pillar / config required to test the proposed changes

n/a

### Debug log showing how the proposed changes work

n/a

### Documentation checklist

- [ x] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2021-05-28 14:24 UTC, dafyddj commented
Hi, and thanks for your contribution. Could you shorten the commit message title to 72 chars as noted by the failing `commitlint` check?

2021-05-28 14:50 UTC, myii requested changes
Please fix the formatting as suggested.

2021-05-28 14:50 UTC, myii commented on docs/README.rst
> +Git repositories under ``/srv/formulas`` and makes them available in the relevant ``file_roots`` settings. Please note that in order for `file_roots` to be updated, `salt.master` must be called after
Need to use double-backticks in reStructuredText:

```suggestion
Git repositories under ``/srv/formulas`` and makes them available in the relevant ``file_roots`` settings. Please note that in order for ``file_roots`` to be updated, ``salt.master`` must be called after ``salt.formulas``. For example:
```

@dafyddj I'm sure one of our linters was supposed to catch this but that doesn't seem to be the case.  Any ideas?

2021-05-30 21:47 UTC, droope commented
Hi.

I made the changes you requested:

* Shortened the commit message.
* Used double backticks instead of single backticks.

2021-06-02 15:02 UTC, merged

2021-06-02 21:05 UTC, droope commented
Oh thank you! awesome 👍🏼